import { LinkedList } from "./linked-list.js";
const list = LinkedList();
list.append("node 1");
list.append("node 2");
list.append("node 3");
list.append("node 4");
list.append("node 5");
list.append("node 6");
list.append("node 7");
list.prepend("node -1");
list.prepend("node -2");
list.prepend("node -3");
// list.pop();
// list.pop();
// list.pop();
// list.pop();
// list.pop();
list.insertAt("node 2.5", 10);
list.remvoeAt(9);
console.log(list.toString());
console.log(list.size());
console.log(list.head());
console.log(list.tail());
console.log(list.at(9));
console.log(list.contains("node 4"));
console.log(list.find("node 4"));